[book]
authors = ["Justin Huang"]
language = "en"
multilingual = false
src = "src"
title = "IB Computer Science"
description = "A textbook for the IB Computer Science Curriculum. Written by students, for students!"
